spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: sad
            client-secret:
            scope:
              - email
              - public_profile